language: node_js
node_js:
  - "14"
script:
  - echo 'Installing Dependencies'
  - npm install
  - echo 'Building with lerna'
  - npm run lerna bootstrap
  - npm run lerna run test --scope=@rapidcode/app
  - npm run lerna run build
  - echo 'End Build'
