language: node_js
node_js:
  - "14"
script:
  - echo 'Installing Dependencies'
  - npm install
  - echo 'Building with lerna'
  - npm run lerna bootstrap
  - npm run lerna run build
  - echo 'Versioning with lerna'
  - npm run lerna version -- --no-push
  - echo 'End Build'
