language: node_js
node_js:
  - "14"
script:
  - echo 'Installing Dependencies'
  - npm install
  - echo 'Building with lerna'
  - npm run lerna bootstrap -- --hoist
  - npm run lerna run test -- --scope=@rapidcode/app --scope=@rapidcode/route
  - npm run lerna run build
  - echo 'End Build'
